# Generated by Django 2.2.6 on 2020-01-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='name',
        ),
        migrations.AddField(
            model_name='wish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
