# Generated by Django 2.2.6 on 2020-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200103_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.CharField(default='go home', max_length=100),
            preserve_default=False,
        ),
    ]
